### ISSUE TITLE
Create Employee welcome page with options for crUD operations, view and add quizzes

### ISSUE THREAD

**Issue by Schnaidm** [GregoryNavasarkian/software-programming-quiz#27]

**Comment by GregoryNavasarkian** [comment]
This code should make the initial screen a bit easier. It looks like this: 

![image](https://user-images.githubusercontent.com/111259248/234128470-0521ce86-2ad2-484a-a19f-ab270930ca6a.png)


```javascript

export default function Example() {
  return (
    <div className="text-center">
      <svg
        className="mx-auto h-12 w-12 text-slate-500"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path
          vectorEffect="non-scaling-stroke"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
        />
      </svg>
      <h3 className="mt-2 text-sm font-semibold text-gray-900">No projects</h3>
      <p className="mt-1 text-sm text-gray-500">Get started by creating a new project.</p>
      <div className="mt-6">
        <button
          type="button"
          className="inline-flex items-center rounded-md bg-slate-700 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-slate-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-800"
        >
          Create Quiz
        </button>
      </div>
    </div>
  )
}

```

**Comment by GregoryNavasarkian** [comment]
This is my idea for the create quiz. Let me know what you think.

![image](https://user-images.githubusercontent.com/111259248/234130809-4084a4fd-fe69-4b2f-bb41-9da390022eec.png)
![image](https://user-images.githubusercontent.com/111259248/234130824-d40cc191-e328-4608-b0d6-cfe96fdf2702.png)

**Comment by Schnaidm** [comment]
looks good - kinda what I thought too re the create quiz.

I did already work on the dashboard before seeing this - this is what I was thinking (I figured if you click on the view quizzes and there are none to view, it will give an alert.
What do you think? Should I rather switch it?

![image](https://user-images.githubusercontent.com/76974953/234167061-e0c28321-d205-4219-a591-ff524f5d7d99.png)

**Comment by GregoryNavasarkian** [comment]
Thats basically what I was thinking just without the view quizzes. 
I think it should just be the thing I posted above if there are not any quizzes, and if there are some then it will just populate on the screen. 
Buttons will still be on the top though. Without the view quizzes since they will be populated there already. Same idea just less pages to deal with :)

**Comment by GregoryNavasarkian** [comment]
We can also use this tailwind component [here](https://tailwindui.com/components/application-ui/elements/dropdowns)

![image](https://user-images.githubusercontent.com/111259248/234171653-bbb26700-5b92-45a4-8b6a-6f1709a4f2f8.png)

**Comment by Schnaidm** [comment]
Okay, sound great. Let me get a little further and see how it goes
