### ISSUE TITLE
Fix Landscape Layout on Mobile Devices

### ISSUE THREAD

**Issue by GregoryNavasarkian** [GregoryNavasarkian/software-programming-quiz#9]
The content is cut off when switching to landscape layout on mobile devices.

**Comment by GregoryNavasarkian** [comment]
Need to use landscape: for elements like text. It thinks it is md instead of sm due to the width of the screen.

**Comment by Schnaidm** [comment]
okay. Just wondering - I dont think its a requirement for this to work on mobile devices? or is it?

**Comment by GregoryNavasarkian** [comment]
Not a requirement but if we have time I want to bo back and optimize some of the design.
